version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LANG=en_US.UTF-8
    ports:
      - "8081:8081"
    depends_on:
      - database
  database:
    image: postgres:15.2
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
